### ISSUE TITLE
Add kubectl tbac edit <resource>

### ISSUE THREAD

**Issue by anderseknert** [Bisnode/kubectl-tbac#19]
Just dispatching to `kubectl --namespace <namespace> edit resource <resource>`

**Comment by mdanielolsson** [comment]
With the current version's `patch` command it's possible to modify the secret **data** using the `--data` and `--remove-data` flags. These actions can be performed:
- make updates to existing fields
- add new fields
- delete selected fields

It's not possible to modify other fields like labels etc, so I thiunk this would be the usecase for an edit command.

**Comment by mdanielolsson** [comment]
I think the new --export flag is an okay complement to the patch command without too much logic.
