### ISSUE TITLE
tbac patch secret <name> without command does.. something

### ISSUE THREAD

**Issue by anderseknert** [Bisnode/kubectl-tbac#20]
It's not clear to me what this does in terms of modification:
```
kubectl tbac patch secret fix-time-default-default
secret/fix-time-default-default modified
```
Should this not be an error presenting the commands?

**Comment by mdanielolsson** [comment]
Yes, this should be fixed. What it does is that it sends a patch with the same data. We should add a check to require an update on the patch command and exit if it doesn't contain an update.
