### ISSUE TITLE
Add  a feature for creating a secret from a file (--from-file).

### ISSUE THREAD

**Issue by jferrater** [Bisnode/kubectl-tbac#38]
Kubernetes Secret supports creating a secret from a file with `--from-file` option. 

Example:
``kubectl create secret generic <name> --from-file=./keystore.jks``

It would be good to add this feature as well in kubectl-tbac.

**Comment by mdanielolsson** [comment]
We've decided not to support this since we don't want to encourage people to use files that may leave files hanging around on peoples computers containing secrets. So for those who really want to do it this way - the workaround is to use native kubectl commands.
